# This file is read and used when generating cloud-init user-data, any repository and package listed here will be
# added to an NCN during cloud-init.
---
# All repos need to use a URL that is available during the PIT and after the PIT is gone, but resolves to the correct
# nexus in either context.
# The `packages` URL resolves to the PIT nexus and the Kubernetes nexus when in a bootstrap
# and runtime environment (respectively).
zypper:
  repos:
    - id: csm-noos
      name: csm-noos
      baseurl: "https://packages.local/repository/csm-noos?ssl_verify=no"
      enabled: 1
      autorefresh: 1
      gpgcheck: 1
      repo_gpgcheck: 0
    # Use Zypper friendly variables so the correct service pack repository is added.
    # NEVER force add a distro repository, or packages that do care about the distro version can break.
    - id: csm-sle
      name: "csm-sle-${releasever_major}sp${releasever_minor}"
      baseurl: "https://packages.local/repository/csm-sle-${releasever_major}sp${releasever_minor}?ssl_verify=no"
      enabled: 1
      autorefresh: 1
      gpgcheck: 1
      repo_gpgcheck: 0
# List of packages to install. These do not need version pins, because the latest version in nexus is determined by this
# tarball. Version pinning here would be redundant, and likely lead to more failures if anyone neglected updating it.
packages:
  - cani
  - canu
  - cray-cmstools-crayctldeploy
  - craycli
  - csm-testing
  - goss-servers
  - hpe-csm-goss-package
  - iuf-cli
  - libcsm
  - platform-utils
  - sma-cli-utils
