apiVersion: manifests/v1beta1
metadata:
  name: core-services
spec:
  sources:
    charts:
    - name: csm-algol60
      type: repo
      location: https://artifactory.algol60.net/artifactory/csm-helm-charts/
  charts:

  # HMS
  - name: cray-hms-sls
    source: csm-algol60
    version: 3.0.1
    namespace: services
  - name: cray-hms-smd
    source: csm-algol60
    version: 4.0.0
    namespace: services
    values:
      global:
        appVersion: 1.58.5
        testVersion: 1.58.5
      cray-service:
        sqlCluster:
          resources:
            requests:
              cpu: "4"
              memory: 8Gi
  - name: cray-hms-meds
    source: csm-algol60
    version: 2.0.3
    namespace: services
  - name: cray-hms-reds
    source: csm-algol60
    version: 2.1.3
    namespace: services
  - name: cray-hms-discovery
    source: csm-algol60
    version: 2.0.5
    namespace: services

  # Cray DHCP Kea
  - name: cray-dhcp-kea
    source: csm-algol60
    version: 0.10.23 # update platform.yaml cray-precache-images with this
    namespace: services

  # Cray DNS unbound (resolver)
  - name: cray-dns-unbound
    source: csm-algol60
    version: 0.7.21 # update platform.yaml cray-precache-images with this
    namespace: services
    values:
      global:
        appVersion: 0.7.21

  # Cray DNS powerdns
  - name: cray-dns-powerdns
    source: csm-algol60
    version: 0.2.8 # update platform.yaml cray-precache-images with this
    namespace: services

  - name: cray-powerdns-manager
    source: csm-algol60
    version: 0.7.6
    namespace: services
