apiVersion: manifests/v1beta1
metadata:
  name: core-services
spec:
  sources:
    charts:
    - name: csm-algol60
      type: repo
      location: https://artifactory.algol60.net/artifactory/csm-helm-charts/
  charts:

  # HMS
  - name: cray-hms-sls
    source: csm-algol60
    version: 5.1.5
    namespace: services
    swagger:
    - name: sls
      version: v2
      url: https://raw.githubusercontent.com/Cray-HPE/hms-sls/v2.0.0/api/openapi.yaml
  - name: cray-hms-smd
    source: csm-algol60
    version: 7.0.18
    namespace: services
    values:
      cray-service:
        sqlCluster:
          resources:
            requests:
              cpu: "4"
              memory: 8Gi
    swagger:
    - name: smd
      version: v2
      url: https://raw.githubusercontent.com/Cray-HPE/hms-smd/v2.11.12/api/swagger_v2.yaml
  - name: cray-hms-meds
    source: csm-algol60
    version: 2.0.3
    namespace: services
  - name: cray-hms-reds
    source: csm-algol60
    version: 3.0.1
    namespace: services
  - name: cray-hms-discovery
    source: csm-algol60
    version: 2.1.1
    namespace: services

  # Cray DHCP Kea
  - name: cray-dhcp-kea
    source: csm-algol60
    version: 0.10.27 # update platform.yaml cray-precache-images with this
    namespace: services

  # Cray DNS unbound (resolver)
  - name: cray-dns-unbound
    source: csm-algol60
    version: 0.7.26 # update platform.yaml cray-precache-images with this
    namespace: services
    values:
      global:
        appVersion: 0.7.26

  # Cray DNS powerdns
  - name: cray-dns-powerdns
    source: csm-algol60
    version: 0.3.0 # update platform.yaml cray-precache-images with this
    namespace: services

  - name: cray-powerdns-manager
    source: csm-algol60
    version: 0.8.3 # update platform.yaml cray-precache-images with this
    namespace: services
