apiVersion: manifests/v1beta1
metadata:
  name: keycloak-gatekeeper
spec:
  sources:
    charts:
    - name: csm-algol60
      type: repo
      location: https://artifactory.algol60.net/artifactory/csm-helm-charts/
  charts:
  - name: cray-keycloak-gatekeeper
    source: csm-algol60
    version: 1.0.0
    namespace: services
