#
# MIT License
#
# (C) Copyright 2022-2024 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: manifests/v1beta1
metadata:
  name: sysmgmt
spec:
  sources:
    charts:
    - name: csm-algol60
      type: repo
      location: https://artifactory.algol60.net/artifactory/csm-helm-charts/
  charts:

  # HMS
  # Install any operators first, wait for them to come up before continuing.
  - name: cray-hms-bss
    source: csm-algol60
    version: 3.2.2
    namespace: services
    timeout: 10m
    swagger:
    - name: bss
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/hms-bss/v1.26.0/api/swagger.yaml
  - name: cray-hms-capmc
    source: csm-algol60
    version: 5.0.0
    namespace: services
    swagger:
    - name: capmc
      version: v3
      url: https://raw.githubusercontent.com/Cray-HPE/hms-capmc/v3.6.0/api/swagger.yaml
  - name: cray-hms-firmware-action
    source: csm-algol60
    version: 3.1.6
    namespace: services
    swagger:
    - name: firmware-action
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/hms-firmware-action/v1.33.0/api/docs/swagger.yaml
  - name: cray-hms-hbtd
    source: csm-algol60
    version: 3.1.1
    namespace: services
    timeout: 10m
    swagger:
    - name: hbtd
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/hms-hbtd/v1.20.0/api/swagger.yaml
  - name: cray-hms-hmnfd
    source: csm-algol60
    version: 4.0.4
    namespace: services
    timeout: 10m
    swagger:
    - name: hmnfd
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/hms-hmnfd/v1.21.0/api/swagger_v2.yaml
  - name: cray-hms-hmcollector
    source: csm-algol60
    version: 2.16.7
    namespace: services
  - name: cray-hms-scsd
    source: csm-algol60
    version: 3.0.1
    namespace: services
    swagger:
    - name: scsd
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/hms-scsd/v1.19.0/api/openapi.yaml
  - name: cray-hms-rts
    source: csm-algol60
    version: 5.0.0
    namespace: services
  - name: cray-hms-rts
    releaseName: cray-hms-rts-snmp
    source: csm-algol60
    version: 4.0.2
    namespace: services
    values:
      rtsDoInit: false
      environment:
        cray_hms_rts:
          backend_helper: SNMPSwitch
  - name: cray-power-control
    source: csm-algol60
    version: 2.1.8
    namespace: services
    timeout: 10m
    swagger:
    - name: power-control
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/hms-power-control/v2.4.0/api/swagger.yaml

  # CMS
  - name: cfs-ara
    source: csm-algol60
    version: 1.3.0
    namespace: services
  - name: cfs-hwsync-agent
    source: csm-algol60
    version: 1.12.3
    namespace: services
  - name: cfs-trust
    source: csm-algol60
    version: 1.7.4
    namespace: services
  - name: cms-ipxe
    source: csm-algol60
    version: 1.14.2
    namespace: services
  - name: cray-bos
    source: csm-algol60
    version: 2.27.0
    namespace: services
    timeout: 10m
    swagger:
    - name: bos
      version: v2
      url: https://raw.githubusercontent.com/Cray-HPE/bos/v2.27.0/api/openapi.yaml.in
  - name: cray-cfs-api
    source: csm-algol60
    version: 1.20.2
    namespace: services
    swagger:
    - name: cfs
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/config-framework-service/v1.20.2/api/openapi.yaml
  - name: cray-cfs-batcher
    source: csm-algol60
    version: 1.12.0
    namespace: services
  - name: cray-cfs-operator
    source: csm-algol60
    version: 1.27.1
    namespace: services
  - name: cray-console-data
    source: csm-algol60
    version: 2.2.0
    namespace: services
  - name: cray-console-operator
    source: csm-algol60
    version: 1.8.1
    namespace: services
    timeout: 20m0s
  - name: cray-console-node
    source: csm-algol60
    version: 2.3.1
    namespace: services
    timeout: 20m0s
  - name: cray-csm-barebones-recipe-install
    source: csm-algol60
    version: 2.6.0
    namespace: services
    values:
      cray-import-kiwi-recipe-image:
        import_image:
          image:
            # The following version needs to match the above cray-csm-barebones-recipe-install
            # version. Due to included helm charts, it needs to be overridden here as well.
            tag: 2.6.0
        catalog:
          image:
            # The following version is the cray-product-catalog version.
            # Unless there is a specific reason not to, this version should be
            # updated whenever the cray-product-catalog chart version is updated, and
            # vice versa.
            tag: 2.4.0
  - name: cray-ims
    source: csm-algol60
    version: 3.17.1
    namespace: services
    swagger:
    - name: ims
      version: v3
      url: https://raw.githubusercontent.com/Cray-HPE/ims/v3.17.1/api/openapi.yaml
  - name: cray-tftp
    source: csm-algol60
    version: 1.10.2
    namespace: services
  - name: cray-tftp-pvc
    source: csm-algol60
    version: 1.10.2
    namespace: services
  - name: csm-config
    source: csm-algol60
    version: 1.26.0
    namespace: services
    values:
      cray-import-config:
        catalog:
          image:
            # The following version is the cray-product-catalog version.
            # Unless there is a specific reason not to, this version should be
            # updated whenever the cray-product-catalog chart version is updated, and
            # vice versa.
            tag: 2.4.0
        import_job:
          initContainers:
          # This init container will write the desired cray-sat version to vars/main.yml
          # in the csm.ncn.sat role. This allows the loftsman manifest to specify the
          # cray-sat container image version, which means the CSM build can set it to match
          # the version of the container image it packages in the CSM release.
          - name: set-sat-version
            # release.sh sets image at CSM distribution build time
            image: "artifactory.algol60.net/csm-docker/stable/docker.io/library/alpine:3.18"
            volumeMounts:
            - mountPath: /shared
              name: config-overlay
            env:
            - name: CRAY_SAT_VERSION
              # release.sh sets value at CSM release distribution build time
              value: "csm-latest"
            command: ['/bin/sh']
            args:
            - -c
            - 'mkdir -p /shared/roles/csm.ncn.sat/vars/ && echo "sat_container_image_version: $CRAY_SAT_VERSION" > /shared/roles/csm.ncn.sat/vars/main.yml'

  - name: csm-ssh-keys
    source: csm-algol60
    version: 1.6.3
    namespace: services

  - name: gitea
    source: csm-algol60
    version: 2.8.0
    namespace: services

  # Cray Product Catalog
  - name: cray-product-catalog
    source: csm-algol60
    # Unless there is a specific reason not to, this version should be
    # updated whenever the csm-config catalog image version is updated, and
    # vice versa.
    # Also update the catalog:image:tag value in the barebones recipe section.
    version: 2.4.0
    namespace: services

  # Spire service
  - name: spire
    source: csm-algol60
    version: 2.15.5
    namespace: spire
  - name: cray-spire
    source: csm-algol60
    version: 1.6.5
    namespace: spire

  # Tapms service
  - name: cray-tapms-crd
    source: csm-algol60
    version: 0.4.1
    namespace: tapms-operator
  - name: cray-tapms-operator
    source: csm-algol60
    version: 0.4.1
    namespace: tapms-operator
    swagger:
    - name: tapms-operator
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/cray-tapms-operator/v1.5.9/docs/openapi.yaml
