#
# MIT License
#
# (C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: manifests/v1beta1
metadata:
  name: sysmgmt
spec:
  sources:
    charts:
    - name: csm-algol60
      type: repo
      location: https://artifactory.algol60.net/artifactory/csm-helm-charts/
  charts:

  # HMS
  # Install any operators first, wait for them to come up before continuing.
  - name: cray-hms-bss
    source: csm-algol60
    version: 3.1.4
    namespace: services
    swagger:
    - name: bss
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/hms-bss/v1.26.0/api/swagger.yaml
  - name: cray-hms-capmc
    source: csm-algol60
    version: 4.0.2
    namespace: services
    swagger:
    - name: capmc
      version: v3
      url: https://raw.githubusercontent.com/Cray-HPE/hms-capmc/v3.3.0/api/swagger.yaml
  - name: cray-hms-firmware-action
    source: csm-algol60
    version: 3.0.4
    namespace: services
    swagger:
    - name: firmware-action
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/hms-firmware-action/v1.29.0/api/docs/swagger.yaml
  - name: cray-hms-hbtd
    source: csm-algol60
    version: 3.0.2
    namespace: services
    swagger:
    - name: hbtd
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/hms-hbtd/v1.19.1/api/swagger.yaml
  - name: cray-hms-hmnfd
    source: csm-algol60
    version: 4.0.0
    namespace: services
    swagger:
    - name: hmnfd
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/hms-hmnfd/v1.19.0/api/swagger_v2.yaml
  - name: cray-hms-hmcollector
    source: csm-algol60
    version: 2.16.2
    namespace: services
  - name: cray-hms-scsd
    source: csm-algol60
    version: 2.1.5
    namespace: services
    swagger:
    - name: scsd
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/hms-scsd/v1.17.0/api/openapi.yaml
  - name: cray-hms-rts
    source: csm-algol60
    version: 4.0.0
    namespace: services
  - name: cray-hms-rts
    releaseName: cray-hms-rts-snmp
    source: csm-algol60
    version: 4.0.0
    namespace: services
    values:
      rtsDoInit: false
      environment:
        cray_hms_rts:
          backend_helper: SNMPSwitch
  - name: cray-power-control
    source: csm-algol60
    version: 2.0.4
    namespace: services
    swagger:
    - name: power-control
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/hms-power-control/v1.10.0/api/swagger.yaml

  # CMS
  - name: cfs-ara
    source: csm-algol60
    version: 1.1.2
    namespace: services
  - name: cfs-hwsync-agent
    source: csm-algol60
    version: 1.11.0
    namespace: services
  - name: cfs-trust
    source: csm-algol60
    version: 1.6.8
    namespace: services
  - name: cms-ipxe
    source: csm-algol60
    version: 1.11.5
    namespace: services
  - name: cray-bos
    source: csm-algol60
    version: 2.9.0
    namespace: services
    timeout: 10m
    swagger:
    - name: bos
      version: v2
      url: https://raw.githubusercontent.com/Cray-HPE/bos/v2.9.0/api/openapi.yaml.in
  - name: cray-cfs-api
    source: csm-algol60
    version: 1.16.0
    namespace: services
    swagger:
    - name: cfs
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/config-framework-service/v1.16.0/api/openapi.yaml
  - name: cray-cfs-batcher
    source: csm-algol60
    version: 1.9.0
    namespace: services
  - name: cray-cfs-operator
    source: csm-algol60
    version: 1.20.0
    namespace: services
  - name: cray-console-data
    source: csm-algol60
    version: 2.0.0
    namespace: services
  - name: cray-console-operator
    source: csm-algol60
    version: 1.7.0
    namespace: services
    timeout: 20m0s
  - name: cray-console-node
    source: csm-algol60
    version: 2.0.0
    namespace: services
    timeout: 20m0s
  - name: cray-csm-barebones-recipe-install
    source: csm-algol60
    version: 2.2.0
    namespace: services
    values:
      cray-import-kiwi-recipe-image:
        import_image:
          image:
            tag: 2.2.0
  - name: cray-ims
    source: csm-algol60
    version: 3.10.0
    namespace: services
    swagger:
    - name: ims
      version: v3
      url: https://raw.githubusercontent.com/Cray-HPE/ims/v3.10.0/api/openapi.yaml
  - name: cray-tftp
    source: csm-algol60
    version: 1.8.4
    namespace: services
  - name: cray-tftp-pvc
    source: csm-algol60
    version: 1.8.4
    namespace: services
  - name: csm-config
    source: csm-algol60
    version: 1.16.22
    namespace: services
    values:
      cray-import-config:
        catalog:
          image:
            tag: 1.8.12
  - name: csm-ssh-keys
    source: csm-algol60
    version: 1.5.6
    namespace: services
  - name: gitea
    source: csm-algol60
    version: 2.6.3
    namespace: services
    values:
      keycloakImage:
        tag: 3.6.1

  # Cray Product Catalog
  - name: cray-product-catalog
    source: csm-algol60
    version: 1.9.0
    namespace: services

  # Cray UAS Manager service
  - name: cray-uas-mgr
    source: csm-algol60
    version: 1.23.1
    namespace: services
    swagger:
    - name: uas-mgr
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/uas-mgr/v1.23.1/api/swagger.yaml

  - name: update-uas
    source: csm-algol60
    version: 1.8.1
    namespace: services

  # Spire service
  - name: spire
    source: csm-algol60
    version: 2.14.2
    namespace: spire
  - name: cray-spire
    source: csm-algol60
    version: 1.5.4
    namespace: spire

  # Tapms service
  - name: cray-tapms-crd
    source: csm-algol60
    version: 0.3.0
    namespace: tapms-operator
  - name: cray-tapms-operator
    source: csm-algol60
    version: 0.3.0
    namespace: tapms-operator
    swagger:
    - name: tapms-operator
      version: v1
      url: https://raw.githubusercontent.com/Cray-HPE/cray-tapms-operator/v1.5.7/docs/openapi.yaml
