#
# MIT License
#
# (C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: manifests/v1beta1
metadata:
  name: sysmgmt
spec:
  sources:
    charts:
    - name: csm-algol60
      type: repo
      location: https://artifactory.algol60.net/artifactory/csm-helm-charts/
  charts:

  # HMS
  # Install any operators first, wait for them to come up before continuing.
  - name: cray-hms-trs-operator
    source: csm-algol60
    version: 2.0.3
    namespace: operators
  - name: cray-hms-bss
    source: csm-algol60
    version: 2.1.5
    namespace: services
  - name: cray-hms-capmc
    source: csm-algol60
    version: 3.0.6
    namespace: services
  - name: cray-hms-firmware-action
    source: csm-algol60
    version: 2.1.6
    namespace: services
    values:
      global:
        appVersion: 1.24.1
  - name: cray-hms-hbtd
    source: csm-algol60
    version: 2.1.4
    namespace: services
  - name: cray-hms-hmnfd
    source: csm-algol60
    version: 2.1.4
    namespace: services
  - name: cray-hms-hmcollector
    source: csm-algol60
    version: 2.16.0
    namespace: services
    values:
      global:
        appVersion: 2.23.0
      kafkaBrokers:
        - BrokerAddress: cluster-kafka-bootstrap.sma.svc.cluster.local:9092
          TopicsToPublish:
            - cray-telemetry-temperature
            - cray-telemetry-voltage
            - cray-telemetry-power
            - cray-telemetry-energy
            - cray-telemetry-fan
            - cray-telemetry-pressure
            - cray-telemetry-humidity
            - cray-telemetry-liquidflow
            - cray-fabric-telemetry
            - cray-fabric-perf-telemetry
            - cray-fabric-crit-telemetry
            - cray-dmtf-resource-event
            - cray-fabric-health-events
        - BrokerAddress: cray-shared-kafka-kafka-bootstrap.services.svc.cluster.local:9092
          TopicsToPublish:
            - cray-dmtf-resource-event
  - name: cray-hms-scsd
    source: csm-algol60
    version: 2.1.5
    namespace: services
  - name: cray-hms-rts
    source: csm-algol60
    version: 2.0.4
    namespace: services

  # CMS
  - name: cray-ims
    source: csm-algol60
    version: 3.7.2
    namespace: services
  - name: cray-cfs-operator
    source: csm-algol60
    version: 1.16.5
    namespace: services
  - name: cray-cfs-api
    source: csm-algol60
    version: 1.11.2
    namespace: services
  - name: cray-cfs-batcher
    source: csm-algol60
    version: 1.7.34
    namespace: services
  - name: cfs-trust
    source: csm-algol60
    version: 1.6.2
    namespace: services
  - name: cfs-hwsync-agent
    source: csm-algol60
    version: 1.8.1
    namespace: services
  - name: gitea
    source: csm-algol60
    version: 2.5.1
    namespace: services
    values:
      keycloakImage:
        tag: 3.6.1
  - name: cray-console-operator
    source: csm-algol60
    version: 1.6.0
    namespace: services
    timeout: 20m0s
  - name: cray-console-node
    source: csm-algol60
    version: 1.6.0
    namespace: services
    timeout: 20m0s
  - name: cray-console-data
    source: csm-algol60
    version: 1.6.1
    namespace: services
  - name: cray-crus
    source: csm-algol60
    version: 1.11.1
    namespace: services
  - name: cray-tftp
    source: csm-algol60
    version: 1.8.0
    namespace: services
  - name: cray-tftp-pvc
    source: csm-algol60
    version: 1.8.0
    namespace: services
  - name: cms-ipxe
    source: csm-algol60
    version: 1.11.1
    namespace: services
  - name: cray-bos
    source: csm-algol60
    version: 2.0.18
    namespace: services
    timeout: 10m
  - name: csm-ssh-keys
    source: csm-algol60
    version: 1.4.1
    namespace: services
  - name: csm-config
    source: csm-algol60
    version: 1.14.5
    namespace: services
    values:
      cray-import-config:
        catalog:
          image:
            tag: 1.3.1
  - name: cray-csm-barebones-recipe-install
    source: csm-algol60
    version: 1.7.0
    namespace: services
    values:
      cray-import-kiwi-recipe-image:
        import_image:
          image:
            tag: 1.7.0

  # Cray Product Catalog
  - name: cray-product-catalog
    source: csm-algol60
    version: 1.3.1
    namespace: services
  # Cray UAS Manager service
  - name: cray-uas-mgr
    source: csm-algol60
    version: 1.22.1
    namespace: services
  - name: update-uas
    source: csm-algol60
    version: 1.8.1
    namespace: services

  # Spire service
  - name: spire
    source: csm-algol60
    version: 2.10.4
    namespace: spire

  # Tapms service
  - name: cray-tapms-operator
    source: csm-algol60
    version: 0.0.8
    namespace: tapms-operator
